#ifndef SAGE_CONFIG_H
#define SAGE_CONFIG_H

#ifndef SAGE_VERSION
#define SAGE_VERSION "Something went wrong with VERSION"
#endif

#define SAGE_WINDOW_TITLE   "Sage"

#define SAGE_MULTISAMPLE_ANTIALIASING 8

// constants are based off glfwSwapInterval()
#define SAGE_VSYNC_LOCK     1
#define SAGE_VSYNC_UNLOCK   0
#define SAGE_VSYNC_SETTING  SAGE_VSYNC_LOCK

#define SAGE_OPENGL_MAJOR_VERSION 4
#define SAGE_OPENGL_MINOR_VERSION 1

#define SAGE_INITIAL_WINDOW_WIDTH 640
#define SAGE_INITIAL_WINDOW_HEIGHT 480

#define SAGE_INITIAL_VIEWPORT_WIDTH 640
#define SAGE_INITIAL_VIEWPORT_HEIGHT 480

#endif /* SAGE_CONFIG_H */
